<div class="seed-placeholder">
  <div class="seed-placeholder__banner">DEV SEED CONTENT</div>
  <h2>Placeholder Page</h2>
  <p>This page is generated by the dev seed system. It appears only during local development and is excluded from production builds entirely.</p>
  <p>Navigate back to the <a href="/#work">homepage</a> to continue testing pagination, tag filtering, and search.</p>
  <h2>How It Works</h2>
  <p>Seed content is generated in <code>src/lib/data/content-seed.ts</code> and conditionally merged into the content array only when <code>dev === true</code>. Vite replaces <code>dev</code> with <code>false</code> at build time, and Rollup tree-shakes the entire seed module away.</p>
</div>

<style>
  .seed-placeholder__banner {
    background: #f59e0b;
    color: #000;
    padding: 0.5rem 1rem;
    font-family: var(--font-mono);
    font-size: var(--fs-xs);
    font-weight: 700;
    letter-spacing: 0.1em;
    text-align: center;
    border-radius: 0.25rem;
    margin-bottom: 1.5rem;
  }
</style>
